"""Init1

Revision ID: 13e5228214b0
Revises: 0e54042fdba6
Create Date: 2023-07-23 20:15:14.114255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e5228214b0'
down_revision = '0e54042fdba6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_audit_dim', sa.Column('billing', sa.Float(), nullable=True))
    op.add_column('gpt_conversation_fact', sa.Column('total_billing', sa.Float(), nullable=True))
    op.drop_column('gpt_conversation_fact', 'billing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_conversation_fact', sa.Column('billing', sa.INTEGER(), nullable=True))
    op.drop_column('gpt_conversation_fact', 'total_billing')
    op.drop_column('gpt_audit_dim', 'billing')
    # ### end Alembic commands ###
