"""Init2

Revision ID: 515a68033e8c
Revises: 13e5228214b0
Create Date: 2023-07-23 21:42:56.661959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515a68033e8c'
down_revision = '13e5228214b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_conversation_fact', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gpt_conversation_fact', 'is_active')
    # ### end Alembic commands ###
