"""Init3

Revision ID: d7b4d5dcff9a
Revises: 515a68033e8c
Create Date: 2023-08-09 00:53:18.443061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b4d5dcff9a'
down_revision = '515a68033e8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_audit_dim', sa.Column('role', sa.String(), nullable=True))
    op.add_column('gpt_model_dim', sa.Column('input_cost', sa.Float(), nullable=True))
    op.add_column('gpt_model_dim', sa.Column('output_cost', sa.Float(), nullable=True))
    op.drop_column('gpt_model_dim', 'cost')
    op.drop_column('gpt_model_dim', 'input_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gpt_model_dim', sa.Column('input_type', sa.VARCHAR(), nullable=True))
    op.add_column('gpt_model_dim', sa.Column('cost', sa.FLOAT(), nullable=True))
    op.drop_column('gpt_model_dim', 'output_cost')
    op.drop_column('gpt_model_dim', 'input_cost')
    op.drop_column('gpt_audit_dim', 'role')
    # ### end Alembic commands ###
